version: "2.1"
services:
  tinymediamanager:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tinymediamanager
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - ALLOW_DIRECT_VNC=true
      - LC_ALL=en_US.UTF-8 # force UTF8
      - LANG=en_US.UTF-8   # force UTF8
      - PASSWORD=<password>
    volumes:
      - /opt/plexmedia/data/tinymediamanager:/data
      - /opt/plexmedia/data/movies/:/media/movies
      - /opt/plexmedia/data/tv_shows:/media/tv_shows
      - /media/mediaserver:/opt/mediaserver # hier liegen die Mediendaten
    ports:
      - 5900:5900 # VNC port
      - 4000:4000 # Webinterface
    restart: unless-stopped